import type { Metadata } from "next";
import { Mona_Sans, TikTok_Sans } from "next/font/google";

import "./globals.css";
import "swiper/css";

import Navbar from "@/components/Navbar";

const monaSans = Mona_Sans({
  variable: "--font-mona-sans",
  subsets: ["latin"],
});

const tiktokSans = TikTok_Sans({
  variable: "--font-tiktok-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${monaSans.variable} ${tiktokSans.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
